
blank_issues_enabled: false
contact_links:
  - name: ğŸŸï¸ Open a Ticket
    url: https://www.gmodstore.com/help/tickets/create/addon/7488
    about: Open a ticket for urgent help, or bigger issues.
  - name: ğŸ’¬ Join the Discord
    url: https://discord.gg/BDUevy7b8w
    about: Join the Discord for questions or minor issues.
